title: "Мой сайт с Jekyll и статическими страницами"
description: "Это пример, который показывает, как сочетать Jekyll и статические страницы."
baseurl: ""  # Используй, если сайт размещен в подкаталоге
theme: minima
exclude:
  - custom-pages/  # Исключаем папку с кастомными страницами из обработки Jekyll
  - static/
